services:
  - type: web
    name: aadvita
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: aadvita-db
          property: connectionString
  - type: pspg
    name: aadvita-db
    databaseName: aadvita
    user: aadvita_user
    plan: free

